#!/usr/bin/with-contenv sh

if [ -z "$RCLONE_REMOTE_MOUNT" ]; then
  echo "Error: RCLONE_REMOTE_MOUNT environment variable was not passed to the container."
  exit 1
fi

rclone_conf_path=$(grep -P "rclone_config_path" ${CLOUDPLOW_CONFIG} | awk -F: '{print $2}' | awk -F\" '{print $2}')

mount_command="rclone mount --config=$rclone_conf_path --allow-other $RCLONE_MOUNT_OPTIONS $RCLONE_REMOTE_MOUNT /cloud"

echo "Executing => $mount_command"
exec \
	s6-setuidgid abc $mount_command